name: libraryproject
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  image_picker: ^0.8.5+3
  dio: ^5.7.0
  json_serializable: ^6.9.3
  json_annotation: ^4.9.0
  http_parser: ^4.1.2
  smooth_page_indicator: ^1.2.0+3


dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/


  fonts:
    - family: Vazir
      fonts:
        - asset: assets/fonts/Vazir-Thin.ttf
          weight: 100
        - asset: assets/fonts/Vazir-Light.ttf
          weight: 300
        - asset: assets/fonts/Vazir-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazir.ttf
          weight: 700
        - asset: assets/fonts/Vazir-Bold.ttf
          weight: 900

    - family: Samim
      fonts:
        - asset: assets/fonts/Samim.ttf
    - family: Ordibehesht
      fonts:
        - asset: assets/fonts/o.ttf
    - family: Sahel
      fonts:
        - asset: assets/fonts/Sahel.ttf

